### ISSUE TITLE
High resolution problems

### ISSUE THREAD

**Issue by summerwbb** [lyndonzheng/Pluralistic-Inpainting#50] opened 2020-03-26 05:56 UTC
Thank you very much for sharing the code.
Can I test the high resolution image directly on the pre training model? In addition, can I train high-resolution images? For example, 1024.
I used the pre training model to test 512 resolution, and the result was very poor.

**Comment by lyndonzheng** [comment] 2020-03-27 01:53
This is a duplicate of https://github.com/lyndonzheng/Pluralistic-Inpainting/issues/17

**Closed** 2021-01-24 02:08 UTC
