### ISSUE TITLE
About pre-trained model

### ISSUE THREAD

**Issue by huytran19** [lyndonzheng/Pluralistic-Inpainting#60] opened 2021-03-24 09:54 UTC
I want to test your project so I downloaded your pre-trained model, but result image is different, it is just define the mask that I drew, please explain for me, please.

**Comment by lyndonzheng** [comment] 2021-04-19 01:15
Hi @huytran19, This is a duplicate of https://github.com/lyndonzheng/Pluralistic-Inpainting/issues/9 and https://github.com/lyndonzheng/Pluralistic-Inpainting/issues/40

**Closed** 2021-08-05 23:00 UTC
