### ISSUE TITLE
Question about the output of Discriminator

### ISSUE THREAD

**Issue by samblack15** [lyndonzheng/Pluralistic-Inpainting#44] opened 2020-01-07 19:35 UTC
When I feed a 1x3x512x512 tensor to the discriminator (representing a single RGB image with height and width = 512) the output is a 1x1x14x14 tensor. Why is it not just one single number? How can I interpret this discriminator output to determine whether it thinks that the image is real or fake?

**Comment by lyndonzheng** [comment] 2020-01-08 08:41
@samblack15 This is a duplicate of the [issue in PatchGAN](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/39).

**Closed** 2021-01-24 02:08 UTC
